### ISSUE TITLE
UX Enhancement request

### ISSUE THREAD

**Issue by BLumia** [chirs241097/QMidiPlayer#4]
![p1](https://cloud.githubusercontent.com/assets/10095765/22864065/378800a4-f185-11e6-9ee1-92d74d17947e.png)
This text area require user input file path, maybe using QFileDialog is a good idea.

If user close Channel, FX and Playlist dialog by clicking the close button on the dialog window (not by clicking the button on QMidiPlayer main window), these dialog may automate open when user run QMidiPlayer next time.

The toggle state of these dialog should be more directviewing so user can now a switcher button state is `on` or `off` .

Should warn user if no soundfont loaded.

Gary W.

**Comment by chirs241097** [comment]
1. Has once been considered but requires a weird API to implement. And this is *not* a rare approach: ~~the fluidsynth plugin of vlc uses plain text area for entering path to soundfonts and the default value is blank...~~ Anyhow this change has low priority because these options _should_ be seldomly used. I'd rather make the plugin able to find the fonts first.

2. Unreproducible for me on Linux or Windows Vista.

3. Blame the theme of Windows 10, which sucks a lot. The feature you mentioned here has been implemented since the very first day of development.

4. Scheduled for the next commit.

Thanks for the feedback.

Chris
