### ISSUE TITLE
Software crashes after closing the visualizer window or stop the play back(when the visualizer is on).

### ISSUE THREAD

**Issue by LovelyA72** [chirs241097/QMidiPlayer#8]
I tried to tweak everything in the setting, however, it doesn't solve.
I'd like to attach a log file, can you please tell me where can I find it?

This issue happens both in 2D and 3D mode

Operating system: Windows 10 update 1803
Graphics card: NVIDIA Quadro M2200

**Comment by chirs241097** [comment]
Would be really helpful if you provide the revision of QMidiPlayer you are using.
As for logs, you may capture `stderr` and post it here.

**Comment by LovelyA72** [comment]
The version of the software is 0.8.3-2, the newest release on GitHub.

**Comment by chirs241097** [comment]
The bug you are referring to was probably already fixed by 37ba9dd1ce449bc2c2f422dd04225bc68bd89c59. I've just put up a new snapshot build with that commit incorporated [here](https://github.com/chirs241097/QMidiPlayer/releases/tag/0.8.6_fluidsynth-2.x_alpha_1).

Please note this build is not thoroughly tested. Bug reports regarding this release are welcomed.

**Comment by LovelyA72** [comment]
This release solved the visualization crashing issue. But raised another issue which is the software need to restart to apply a SoundFont change.
Should I keep this issue open or open a new issue and close this one?

**Comment by chirs241097** [comment]
Glad to hear your issue is resolved.

Did you mean a manual restart or an unexpected termination of the program by saying 'the software need to restart'?

If it is a manual restart, that's intentional. You can also use 'Restart fluidsynth' option found in the context menu of the song name label.

Otherwise it's likely a bug. You may open a new issue for that.

Closing current issue as resolved.
